name: CI
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: setup-server
        - uses: actions/setup-node@v2
          with:
            node-version: '16.10.0'
            cache: 'yarn'
      - name: setup-repo
        - uses: actions/checkout@v2
        - run: |
          choco install wget --no-progress 
          wget --user='${{ secrets.C3D_DOWNLOAD_USER }}' --password '${{ secrets.C3D_DOWNLOAD_PASS }}' https://c3d.sd.ascon.ru/C3D_workversion/C3D_Kernel_Latest/Kernel/Win64_Visual_Studio_2019_Unicode.zip
          7z x Win64_Visual_Studio_2019_Unicode.zip -ovendor/c3d/
          yarn install
          echo '${{ secrets.C3D_LICENSE_KEY_WIN }}' > "license-key.json"
      - name: build
        - run: |
          choco install astyle
          yarn generate
          yarn run node-gyp rebuild -j max
      - name: test
        - run: yarn test
      - name: canary-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: |
          yarn electron-rebuild
          yarn publish