name: CI
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Post
        run: |
          choco install curl --no-progress
          curl -H "Content-Type: application/json" -d "{\"username\": \"GitHub\", \"content\": \"https://github.com/nkallen/plasticity/releases/tag/v$(echo hi)\"}" '${{ secrets.DISCORD_WEBHOOK_URL }}'
          curl -H "Content-Type: application/json" -d "{`"username`": `"GitHub`", `"content`": `"https://github.com/nkallen/plasticity/releases/tag/v0`"}" '${{ secrets.DISCORD_WEBHOOK_URL }}'
          curl -H "Content-Type: application/json" -d '{"username": "GitHub", "content": "https://github.com/nkallen/plasticity/releases/tag/v1"}' '${{ secrets.DISCORD_WEBHOOK_URL }}'
