name: CI
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Post
        run: |
          choco install curl --no-progress
          curl --% -H "Content-Type: application/json" -d "{\"username\": \"GitHub\", \"content\": \"https://gi0thub.com/nkallen/plasticity/releases/tag/v$(echo 1)\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
