name: Discord
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: next
        run: |
          yarn echo-version
          curl -H "Content-Type: application/json" -d "{\"username\": \"test\", \"content\": \"https://github.com/nkallen/plasticity/releases/tag/v`yarn echo-version`\"}" '${{ secrets.DISCORD_WEBHOOK_URL }}'