name: Discord
on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'yarn'
      - run: |
        curl -H "Content-Type: application/json" -d '{"username":"test", "content":"hello"}' '${{ secrets.DISCORD_WEBOOK_URL }}'
