name: Discord
on: [push]
jobs:
  notify:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.10.0'
      #     cache: 'yarn'
      # - name: Yarn install
      #   run: |
      #     yarn install
      # - name: Post
      #   run: |
      #     choco install curl --no-progress
      #     yarn echo-version
      #     curl -H "Content-Type: application/json" -d "{`"username`": `"GitHub`", `"content`": `"https://github.com/nkallen/plasticity/releases/tag/v$(yarn echo-version)`"}" '${{ secrets.DISCORD_WEBHOOK_URL }}'
      #     curl --% -H "Content-Type: application/json" -d "{\"username\": \"GitHub\", \"content\": \"https://gi0thub.com/nkallen/plasticity/releases/tag/v$(echo 1)\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}

